apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: test-app
spec:
  containers:
  - name: test-cntnr
    image: luksa/kubia
    ports:
    - containerPort: 8080
      protocol: TCP
